version: "3.8"

services:
  app:
    build: .
    image: firebase-node18
    tty: true
    container_name: firebase-node18-dev
    volumes:
      - ~/workspace/:/home/node/workspace
      - ~/.ssh:/home/node/.ssh:ro
