version: "3.8"

services:
  ubuntu:
    build: .
    image: ubuntu-dev
    tty: true
    container_name: ubuntu-dev
    volumes:
      - ~/workspace/:/home/ubuntu/workspace
      - ~/.ssh:/home/ubuntu/.ssh:ro
